trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'uopsb-app/lib/db.sql'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    sudo apt-get update
    sudo apt-get install -y postgresql-client
  displayName: 'Install PostgreSQL tools'

- script: |
    # Use pipeline variables for PostgreSQL connection information
    server_name="$(DB_HOST)"
    server_admin_login="$(DB_USER)"
    server_admin_password="$(DB_PASSWORD)"
    server_fqdn="$(DB_HOST)"
    database_name="$(DB_NAME)"

    # Connect to the PostgreSQL instance and execute the db.sql file
    PGPASSWORD=$server_admin_password psql -h $server_fqdn -U $server_admin_login@$server_name -d $database_name -f uopsb-app/lib/db.sql
  displayName: 'Connect and execute db.sql'