name: Node.js CI

# Triggers the workflow on push events for the master branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks out your repository's code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Sets up Node.js version 20.x
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'uopsb-app/package-lock.json'

    # Installs dependencies, builds, and runs tests in the correct directory
    - name: Install, build, and test
      working-directory: ./uopsb-app
      run: |
        npm install
        npm run build
        npm test